---
title: '2020-08-17'
author: "Ruoyu"
date: "8/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE)

library(tidytuesdayR)
library(tidyverse)
library(skimr)
library(waffle)
library(dplyr)
```

```{r data}
tuesdata <- tidytuesdayR::tt_load('2020-08-18')

plants <- tuesdata$plants

threats <- tuesdata$threats

actions <- tuesdata$actions
```

```{r extinct_country}
extinct_country <- plants %>% 
  select(-c(threat_AA:action_NA)) %>% 
  filter(red_list_category == "Extinct") 

extinct_country_tidy <- extinct_country %>% 
  count(country) %>%  
  mutate(country = as_factor(country),
         number_of_species = as.numeric(n)) %>% 
  mutate(country = fct_reorder(country, number_of_species,
                               .desc = TRUE))

extinct_country_top10 <- extinct_country_tidy %>% 
  top_n(10) %>% 
  mutate(country = fct_reorder(country, number_of_species,
                               .desc = FALSE))
```

```{r country_plot}
ggplot(data = extinct_country_top10, 
       aes(x = number_of_species, y = country)) +
  geom_col(aes(fill = country), 
           show.legend = FALSE)+
  geom_text(aes(label = paste0(number_of_species)),
            hjust = "inward") +
  labs(x = "Number of Extinct Category Species",
       y = "",
       title = "Top 10 Countries of Extinct Plant Species")+
  theme_classic()

```


```{r threats}
threats_tidy <- threats %>% 
  filter(red_list_category == "Extinct") 

# ggplot(threats_count, aes(fill = group, values = n))+
#   geom_waffle(color = "white", size = .25,
#               n_rows = 10, flip = TRUE)+
#   facet_wrap(~continent, nrow = 1,
#              strip.position = "bottom") +
#   scale_x_discrete() + 
#   scale_y_continuous(labels = function(x) x * 10, # make this multiplyer the same as n_rows
#                      expand = c(0,0)) +
#   labs(
#     title = "Faceted Waffle Bar Chart",
#     subtitle = "{dplyr} storms data",
#     x = "Year",
#     y = "Count"
#   ) +
#   theme_minimal(base_family = "Roboto Condensed") +
#   theme(panel.grid = element_blank(), axis.ticks.y = element_line()) +
#   guides(fill = guide_legend(reverse = TRUE))
```

 unique(threats$group)
[1] "Flowering Plant" 
[2] "Ferns and Allies"
[3] "Cycad"           
[4] "Mosses"          
[5] "Algae"           
[6] "Conifer"

```{r FloweringPlant, fig.width=10}
flower_threats <- threats_tidy %>% 
  filter(group == "Flowering Plant",
         threatened == "1") %>% 
  count(continent, threat_type)

ggplot(flower_threats, aes(fill = threat_type, values = n))+
  geom_waffle(color = "white", size = .25,
              n_rows = 10, flip = TRUE)+
  facet_wrap(~continent, nrow = 1,
             strip.position = "bottom") +
  scale_x_discrete() +
  scale_y_continuous(labels = function(x) x * 10, # make this multiplyer the same as n_rows
                     expand = c(0,0)) +
  labs(
    title = "Extinct Flowering Plants and their threats",
    x = "Continent of Species Originated",
    y = "Count",
    fill = "Threat Type"
  ) +
  theme_minimal(base_family = "Times New Roman") +
  theme(panel.grid = element_blank(), axis.ticks.y = element_line()) +
  guides(fill = guide_legend(reverse = TRUE))
```






